### ISSUE TITLE
Feedback on the structure of the document

### ISSUE THREAD

**Issue by marcodelapierre** [PawseySC/Pawsey-CernVM-FS#1]
Hi @audreystott , sorry I just got back to this one today!
I have a couple of feedback points for your consideration:
- consider providing a section title to the first part of the text, eg similar to Sarah's SHPC/Spack (https://github.com/SarahBeecroft/shpc_doc), **What is CernVM-FS and why is it useful?**
- for BioCommons documentation, we might want to use a kind of standard template, again similar to what is in Sarah's docs, having as sections a "what and why", a "how to install", and an example of how to use
- with this in mind, consider creating a final section with usage example, which could actually just be a cut and paste from the current first part of text:
    > Users will simply access the data sets as though part of their file system, e.g. accessing the Galaxy project's data repository web server (Stratum 1) is as simple as this:
    > ```
    > ls /cvmfs/data.galaxyproject.org
    > ```
    > Once the above path is cached, the user can explore all repositories under /cvmfs. When running analyses, the reference file need only be pointed to the appropriate directory path.

What do you think?

Thanks,

**Comment by audreystott** [comment]
Hi Marco

I agree with all of the above. It makes it much more readable too. I have committed the changes. Thanks!

Audrey

**Comment by marcodelapierre** [comment]
closing this issue then :)
